services:
  web:
    container_name: splink-web
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    restart: unless-stopped

  api:
    container_name: splink-api
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
    restart: unless-stopped

  db:
    container_name: splink-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped



volumes:
  mongo_data:
    driver: local
  node_modules: {}